### PR TITLE
✨ add ascii to export landscapes to a grid

### PR DESCRIPTION
**Pull request by tpoisot**
`ascii` function (currently unchecked) - do we want something to *read* asc files?

### CODE REVIEW

**Comment by mkborregaard** [comment]
Actually do we even want this function here? It seems a bit off. Given our in-place functions I guess we should aim to be able to `rand!` any geographic type and do stuff with it afterwards using the relevant package. Just a stray thought.

**Review by mkborregaard — APPROVED** [review]
I guess we can put it in for now just for feature parity

**Comment by tpoisot** [comment]
I'm less and less convinced we want it because, writedlm is right there. It would make sense to have in SimpleSDMLayers (in fact that's on my to-do list for soon), but I don't really see the value added here.

**Comment by mkborregaard** [comment]
Agreed

**Comment by rafaqz** [comment]
You can also write to ascii or whatever you want with GeoData.jl (ascii is via GDAL, theres a built in version, I just never merged it, because GDAL can...). Its still a little clunky but Im working on some simplifying methods to guess the backend now that things work pretty well. The syntax should be as easy as:

```julia
write("filename.ext", geoarray(A))
```

If you dont care about the lat/lon order.

**Comment by mkborregaard** [comment]
Yes that's the point exactly - if you want spatial types you'd have one of these packages loaded already. Raf, do you think the `rand!` functions here could run on a GeoData raster already?

**Comment by rafaqz** [comment]
Thats interesting - calling `rand!` directly on an existing `GeoArray` to use an existing spatial extent. It should just work with `AbstractArray` fallbacks I guess.

**Comment by mkborregaard** [comment]
That's the plan! Could you try it?

**Pull request closed without merging**
