### PR TITLE
[wip][rfc] New readme from Fig1; fix #42

### LINKED ISSUE #42: Readme organisation
I'd suggest having the readme show the code (and result) of repeating Fig 1 of the paper here: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12308

The Python code for doing it is here: https://besjournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2F2041-210X.12308&file=mee312308-sup-0002-dataS2.py

And then maybe below our planned benchmarking exercise.

### PR DESCRIPTION
**Pull request by mkborregaard**
This adds a readme that recreates Fig1 of the NLMpy paper as suggested in #42. 

This is their Fig1:
billede

This is the one of this PR:
Fig1

The code here ports this file https://besjournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2F2041-210X.12308&file=mee312308-sup-0002-dataS2.py
to our julia format. As you can see there are some discrepancies that we could revisit to make our syntax more intuitive.

I also don't really know about Fig1s, and of course I just need to update the colors on the classified ones.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Now with updated colors
Fig1

**Comment by tpoisot** [comment]
AMAZING 👀

**Comment by tpoisot** [comment]
I'm going to be my usual self and say: can we update the discrete color palette with something that is accessible, like Wong or IBM?

**Comment by mkborregaard** [comment]
I agree that would be nice, but isn't there something to be said for choosing the exact same one as the original paper?

**Comment by tpoisot** [comment]
I'm all for reproducibility, but I think it's better to make a point about accessible color schemes - it wouldn't change the message, and it would make the figure accessible to ~ 10% of people with different color perception.

**Review by tpoisot — APPROVED** [review]

**Review by rafaqz — APPROVED** [review]

**Comment by rafaqz** [comment]
Looks great. I'm just wondering why the Y axis seems to be flipped in d and e in our version?

**Comment by mkborregaard** [comment]
@tpoisot in fact this is one of the high-quality color schemes from RColorBrewer, which are all vetted for accessibility and scientific accuracy. I'm a 100% in agreement with making a statement for using high-quality accessible color schemes, but don't think we should support the notion that this restricts us to a very small portion of schemes, like wong. Even for full color deficiency it should be possibly to tell these apart, with possibly a slight issue for 100% deuteranopics:

Screenshot 2021-02-27 at 11 46 14

 if you like, maybe we can use a different color scheme for the docs?

@rafaqz because Plots and matplotlib interpret matrix orientation differently in heatmap. "Correct" matrix orientation is a real religion among plotting packages.

**Comment by tpoisot** [comment]
Interesting, the simulation plugin I used made the color much less distinguishable than your screenshot - let's go with this then.

**Pull request merged**
