### PR TITLE
fix view shape for perlin

### PR DESCRIPTION
**Pull request by rafaqz**
**What the pull request does**   
Fixes row/ col order in views into the temp square array

**Type of change**   
Please indicate the relevant option(s)

- [x] :bug: Bug fix (non-breaking change which fixes an issue)
- [ ] :sparkle: New feature (non-breaking change which adds functionality)
- [ ] :boom: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] :book: This change requires a documentation update

**Checklist**
- [ ] The changes are documented
  - [ ] The docstrings of the different functions describe the arguments, purpose, and behavior 
  - [ ] There are examples in the documentation website
- [ ] The changes are tested
- [ ] The changes **do not** modify the behavior of the previously existing functions
  - If they **do**, please explain why and how in the introduction paragraph
- [ ] For **new contributors** - my name and information are added to `.zenodo.json`
- [ ] The `Project.toml` field `version` has been updated
  - Change the *last* number for a `v0.0.x` series release, a bug fix, or a performance improvement
  - Change the *middle* number for additional features that *do not* break the current test suite (unless you fix a bug in the test suite)
  - Change the *first* number for changes that break the current test suite

### CODE REVIEW

**Comment by rafaqz** [comment]
We probably need to run all the algorithms for rectangle and square outputs of a few sizes and mix of parameters, not necessarily testing the output just that it works.

**Comment by tpoisot** [comment]
Can you add some tests on combinations of sizes to make sure that it marches?

**Comment by rafaqz** [comment]
I was thinking we should just do that for all of the methods here in one place. Just loop over some sizes/shapes and run them all. I'll look at writing that.

**Comment by rafaqz** [comment]
Ok tests are in the other PR as they may need separate discussion. However this needs to merge for them to pass! I didnt think that through properly...

**Comment by mkborregaard** [comment]
Just merge when you feel confident. We still have 0 users :-)

**Pull request merged**
